### ISSUE TITLE
Host the landing page of rudymap.tw on github

### ISSUE THREAD

**Issue by chihchun** [alpha-rudy/taiwan-topo#33]
The goal is to have the ladning page hosted on [GitHub](https://pages.github.com/), for easier to manage and better SEO for users. The plan is to make docs folder as homepage of rudymap.tw

**Phase 1**
- [x] Update github setings in https://github.com/alpha-rudy/taiwan-topo/settings
  - [x] Select master branch /docs folder as default folder.
  - [x] Enabled "Enforce HTTPS"
  - [x] Verify if we can see http://alpha-rudy.github.io/taiwan-topo/taiwan_topo.html
- [x] Fix the relative link for Garmin files.
- [x] Move /images fodler to docs/
- [x] Convert image syntax to https://kramdown.gettalong.org/syntax.html#images in markdown 
- [x] Move docs/taiwan_topo.md to docs/index.md

**Phase 2**
- [x] Update github setings in https://github.com/alpha-rudy/taiwan-topo/settings
  - [x] Set "rudymap.tw" as "Custom domain"
  - [x] Enabled "Enforce HTTPS"ing 
- [x] Setup domaine name
  - [x] Add a CNAME for rudymap.tw to alpha-rudy.github.io
- [ ] Setup google analytics code in github page, 
  - [ ] If the theme supports google analytics code.
  - [ ] Or Using ga-beacon https://github.com/igrigorik/ga-beacon

**Phase 3**
- [ ] Redirect all traffic to rudymap.tw
 - [ ] Generate a new redirect page using javascript or server-side setting by kcwu and Rex

**Limitation**
- Will not have the "v__version__" version tag in markdown.

**Comment by chihchun** [comment]
I have forked a [repository](https://github.com/chihchun/taiwan-topo) and setup a test host name static.rudymap.tw

* MOI.OSM - Taiwan TOPO (by Rudy) | taiwan-topo - https://static.rudymap.tw/taiwan_topo.html
* 測試版：MOI.OSM - Taiwan TOPO (by Rudy) | taiwan-topo - https://static.rudymap.tw/beta.html

Using Leap day, a Jekyll theme for GitHub Pages - https://github.com/pages-themes/leap-day

**Comment by chihchun** [comment]
Tested 'rdiscount' Markdown engine, received an email from github said the engine is not supported anymore. need to move to kramdown

The 'rdiscount' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/.

**Comment by alpha-rudy** [comment]
Thanks, @chihchun , I will find a time to take a close look!  😄

**Comment by alpha-rudy** [comment]
Hi, @chihchun , **Phase 1** is done. Please take a look (and modify at will if needed). Thanks!  :)

**Comment by alpha-rudy** [comment]
Hi, @chihchun (cc: @typebrook), **Phase 2** cannot be done.  XD

<img width="865" alt="screen shot 2018-09-08 at 4 43 15 pm" src="https://user-images.githubusercontent.com/12744709/45252283-68339280-b386-11e8-8b1f-683bb182b194.png">

**Comment by alpha-rudy** [comment]
嗨， @chihchun , @typebrook , 我很想建置一個魯地圖的網站。

對象應該涵蓋 1) 地圖使用者 2) OSM 製作者 3) 魯地圖製作者

1) 地圖使用者的內容應該涵蓋
1.1) 安裝網頁
1.2) 安裝說明

2) OSM 製作者
2.1) 繪製說明
2.2) 登山 tags 快速檢表

3) 魯地圖製作者
3.1) styles for mapsforge
3.2) styles for garmin GAMP
3.3) GIS data processing
3.4) build machine 建置

我覺得 GitHub 不像 google blogspot 那麼好用，google blogspot 沒有分頁功能。不曉得你們有何建議？

考量兩點：
1) 類似 https://www.openandromaps.org 這樣
2) 可以很多人分工，各自負責不同的 topic

**Comment by typebrook** [comment]
我傾向直接用GitHub Wiki,好的範例可以參考https://github.com/Netflix/Hystrix/wiki
論建置速度和reference的方便性，對「OSM製作者」和「魯地圖製作者」是利多

不過若找得到比較專業的開發者另外架站，對「地圖使用者」來講應該會比較friendly

**Comment by chihchun** [comment]
我們有幾個選項

1. 用 githuab 當作資料處理界面，作者需要學會使用 git 來增添內容。
2. 改用 wordpress 做界面，可以開放給指定作者做維運管理。
3. 改用 discourse 做論壇，可以開放任何人發問或提供內容。

原本命題是取代現在透過 dropbox 分發魯地圖首頁的作法，將 daily build 的網頁改發到 github.  可以重新命題，再來決定解決方案？
